package com.github.jvsena42.mandacaru.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Pink/wine palette, built around 4 brand colors:
// light pink #FBEAF0 (background), medium pink #D4537E (primary/accent),
// wine #993556 (text/outline), dark wine #4B1528 (deep accent / dark-mode base).
// All other roles are tints/blends derived from those four so the whole
// scheme stays visually cohesive; every text/background pairing below was
// checked for WCAG-legible contrast in both light and dark mode.

val primaryLight = Color(0xFFD4537E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEDB5C8)
val onPrimaryContainerLight = Color(0xFF4B1528)
val secondaryLight = Color(0xFF993556)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDEB4C2)
val onSecondaryContainerLight = Color(0xFF4B1528)
val tertiaryLight = Color(0xFF4B1528)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD4BBC4)
val onTertiaryContainerLight = Color(0xFF4B1528)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFBEAF0)
val onBackgroundLight = Color(0xFF4B1528)
val surfaceLight = Color(0xFFFBEAF0)
val onSurfaceLight = Color(0xFF4B1528)
val surfaceVariantLight = Color(0xFFECCFD9)
val onSurfaceVariantLight = Color(0xFF993556)
val outlineLight = Color(0xFF993556)
val outlineVariantLight = Color(0xFFD9ABBA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF72253F)
val inverseOnSurfaceLight = Color(0xFFFBEAF0)
val inversePrimaryLight = Color(0xFFE288A6)
val surfaceDimLight = Color(0xFFE7C6D1)
val surfaceBrightLight = Color(0xFFFBEAF0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFDF2F6)
val surfaceContainerLight = Color(0xFFF3DCE4)
val surfaceContainerHighLight = Color(0xFFEFD4DE)
val surfaceContainerHighestLight = Color(0xFFEBCDD7)

val primaryDark = Color(0xFFE288A6)
val onPrimaryDark = Color(0xFF4B1528)
val primaryContainerDark = Color(0xFF963757)
val onPrimaryContainerDark = Color(0xFFFBEAF0)
val secondaryDark = Color(0xFFC07D94)
val onSecondaryDark = Color(0xFF4B1528)
val secondaryContainerDark = Color(0xFF7E2A46)
val onSecondaryContainerDark = Color(0xFFFBEAF0)
val tertiaryDark = Color(0xFFAC8A96)
val onTertiaryDark = Color(0xFF4B1528)
val tertiaryContainerDark = Color(0xFF621F36)
val onTertiaryContainerDark = Color(0xFFFBEAF0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF4B1528)
val onBackgroundDark = Color(0xFFFBEAF0)
val surfaceDark = Color(0xFF4B1528)
val onSurfaceDark = Color(0xFFFBEAF0)
val surfaceVariantDark = Color(0xFF6E233D)
val onSurfaceVariantDark = Color(0xFFEFBDCE)
val outlineDark = Color(0xFFBB748C)
val outlineVariantDark = Color(0xFF72253F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFBEAF0)
val inverseOnSurfaceDark = Color(0xFF4B1528)
val inversePrimaryDark = Color(0xFFD4537E)
val surfaceDimDark = Color(0xFF4B1528)
val surfaceBrightDark = Color(0xFF8D304F)
val surfaceContainerLowestDark = Color(0xFF310E1A)
val surfaceContainerLowDark = Color(0xFF5F1D34)
val surfaceContainerDark = Color(0xFF6A223A)
val surfaceContainerHighDark = Color(0xFF762741)
val surfaceContainerHighestDark = Color(0xFF822B48)
